# Generated by Django 3.0.7 on 2020-07-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketno', models.CharField(max_length=20, null=True)),
                ('teamname', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('plusrid', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('teamname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.TeamName')),
            ],
        ),
    ]
