# Generated by Django 3.0.7 on 2020-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_inccreddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='increcddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incsolddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
