# Generated by Django 3.0.7 on 2020-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200706_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slamteam',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slasatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
