# Generated by Django 3.0.7 on 2020-07-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200706_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='inccreddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='increcddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='incsolddate',
            field=models.DateTimeField(),
        ),
    ]
