# Generated by Django 3.0.7 on 2020-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20200706_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='inccreddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='increcddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='incsolddate',
            field=models.DateTimeField(null=True),
        ),
    ]
